name: Notify Internal Repo about PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger PR in Internal Repo
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.SUBMODULE_UPDATE_TOKEN }}
          repository: blockfrost/blockfrost-tests-internal
          event-type: public-pr-event
          client-payload: '{"sha": "${{ github.event.pull_request.head.sha }}", "pr_number": "${{ github.event.number }}", "pr_title": "${{ github.event.pull_request.title }}"}'
